language: elixir
elixir:
  - 1.0.2
otp_release:
  - 17.4
sudo: false # to use faster container based build environment
script:
  - mix test --no-start
notifications:
  recipients:
    - rockerboo@gmail.com